name: flecs
channels:
  - conda-forge
  - defaults
  - pyg
  - pytorch
  - bioconda
dependencies:
  - conda-forge::biopython >=1.79
  - matplotlib
  - networkx >=2.6.3
  - numpy >=1.21.2
  - pandas >=1.3.4
  - pyg::pytorch-scatter
  - python >= 3.10
  - pytorch::cpuonly
  - conda-forge::pytorch >=1.12.1
  - scipy >=1.7.1
  - torchdiffeq >=0.2.2
  - nomkl
  - conda-forge::pytorch_geometric >=2.1.0
  - conda-forge::mkdocs
  - conda-forge::mkdocs-material
  - conda-forge::mkdocs-autorefs
  - conda-forge::mkdocstrings
  - conda-forge::mkdocstrings-python
  - bioconda::mygene
  - bioconda::scanpy
  - pip