name: flecs
channels:
  - conda-forge
  - defaults
  - pyg
  - pytorch
  - bioconda
dependencies:
  - pip >=22.2.2
  - conda-forge::biopython >=1.79
  - matplotlib
  - networkx >=2.6.3
  - numpy >=1.21.2
  - pandas >=1.3.4
  - pyg::pytorch-scatter
  - python >= 3.10
  - pytorch >=1.12.1
  - scipy >=1.7.1
  - torchdiffeq >=0.2.2
  - conda-forge::pytorch_geometric >=2.1.0
  - bioconda::mygene
  - bioconda::scanpy
  - pip