# This workflow will run precommit and commit new files on error
#
name: pre-commit

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: >-
      !endsWith(github.event.head_commit.message, '# ci skip') &&
      (
        startsWith(github.ref, 'refs/heads') ||
        github.event.pull_request.draft == false
      )
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v3

      - name: Cache pre-commit
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}-

      - name: Run pre-commit
        id: precommit
        uses: pre-commit/action@v2.0.3
        continue-on-error: true

      - name: Commit files
        if: steps.precommit.outcome == 'failure' && startsWith(github.ref, 'refs/heads')
        run: |
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git checkout -- .github/workflows
            git commit -m "pre-commit" -a
          fi
        shell: bash -e {0}

      - name: Push changes
        if: steps.precommit.outcome == 'failure' && startsWith(github.ref, 'refs/heads')
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Check pre-commit
        if: steps.precommit.outcome == 'failure'
        uses: pre-commit/action@v2.0.3
